### ISSUE TITLE
[BUG] Height param is not supported on private full nodes, but it works on public lcd.terra.dev endpoint

### ISSUE THREAD

**Issue by Zygimantass** [terra-money/core#668] opened 2022-01-25 10:10 UTC
**Describe the bug**

Height param on `wasm/contracts/<address>/store` REST endpoint doesn't work on private full nodes, but works on lcd.terra.dev and gRPC endpoint. However, the header `x-cosmos-block-height: <height>` works on both private full nodes and on the public endpoint. For consistency's sake, it would be better to support the height param on the private full nodes too.

**To Reproduce**
`localhost:1317/terra/wasm/v1beta1/contracts/terra1jxazgm67et0ce260kvrpfv50acuushpjsz2y0p/store?height=6162743&query_msg=eyJwb29sIjoge319` produces a response with `total_share: 590548093388` (among other things).
`localhost:1317/terra/wasm/v1beta1/contracts/terra1jxazgm67et0ce260kvrpfv50acuushpjsz2y0p/store?height=5138774&query_msg=eyJwb29sIjoge319` (notice the different height), also produces a response with `total_share: 590548093388`, which doesn't make sense because there is a height difference of almost a million.

The same queries to the `lcd.terra.dev` endpoint produces different total_share amounts.

**Context & versions**
Tested on private full node versions 0.5.13 and 0.5.14

**(if applicable) suggested solution**
Add the height param to all of the queries in the public build of Terra

**Comment by YunSuk-Yeo** [comment] 2022-02-01 03:02
Did you change app.toml to keep whole state?? 

You need to set pruning option to nothing to use height query.

**Comment by lukanus** [comment] 2022-02-02 18:22
@YunSuk-Yeo this shouldn't matter. The data is there, node is returning the data just fine using cosmos height header @Zygimantass has mentioned. The problem is that height GET parameter is not taken into the account as it's never parsed. Eg. setting height in query string to "asdf" is not returning bad formatting error either.

**Comment by YunSuk-Yeo** [comment] 2022-02-03 00:19
ah ok understood, this problem is already known problem https://github.com/cosmos/cosmos-sdk/pull/10827

**Comment by YunSuk-Yeo** [comment] 2022-02-03 00:21
This cosmos-sdk fix already merged in our custom cosmos-sdk https://github.com/terra-money/cosmos-sdk/commits/v0.44.5-terra.2, so main branch should be find for this

**Closed by YunSuk-Yeo** 2022-02-03 00:21 UTC
Labels: bug
